[project]
name = "weathersimulatr-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cfgrib>=0.9.15.1",
    "eccodes>=2.45.0",
    "herbie-data>=2026.1.0",
    "netcdf4>=1.7.4",
    "xarray>=2026.1.0",
]
